module load languages/intel/2018-u3

sbatch stencil_1.job
sbatch stencil_2.job
sbatch stencil_3.job
sbatch stencil_4.job
sbatch stencil_5.job
sbatch stencil_6.job
sbatch stencil_7.job
sbatch stencil_8.job
sbatch stencil_9.job
sbatch stencil_10.job
sbatch stencil_11.job
sbatch stencil_12.job
sbatch stencil_13.job
sbatch stencil_14.job
sbatch stencil_15.job
sbatch stencil_16.job
sbatch stencil_17.job
sbatch stencil_18.job
sbatch stencil_19.job
sbatch stencil_20.job
sbatch stencil_21.job
sbatch stencil_22.job
sbatch stencil_23.job
sbatch stencil_24.job
sbatch stencil_25.job
sbatch stencil_26.job
sbatch stencil_27.job
sbatch stencil_28.job
sbatch stencil_30.job
sbatch stencil_32.job
sbatch stencil_34.job
sbatch stencil_36.job
sbatch stencil_38.job
sbatch stencil_40.job
sbatch stencil_42.job
sbatch stencil_44.job
sbatch stencil_46.job
sbatch stencil_48.job
sbatch stencil_50.job
sbatch stencil_52.job
sbatch stencil_54.job
sbatch stencil_56.job
